gh label create "feature" --color "1D76DB" --description "New functionality"
gh label create "bug" --color "D73A4A" --description "Something is broken"
gh label create "documentation" --color "0075CA" --description "Documentation updates"
gh label create "refactor" --color "7057FF" --description "Code improvements"
gh label create "test" --color "FBCA04" --description "Testing"
gh label create "chore" --color "BFDADC" --description "Maintenance"

gh label create "cpp" --color "00599C" --description "C++ services"
gh label create "python" --color "3572A5" --description "Python services"
gh label create "frontend" --color "61DAFB" --description "Frontend"
gh label create "kafka" --color "231F20" --description "Kafka related"
gh label create "redis" --color "DC382D" --description "Redis related"
gh label create "postgres" --color "336791" --description "PostgreSQL related"
gh label create "minio" --color "C72E49" --description "MinIO related"
gh label create "docker" --color "2496ED" --description "Docker related"
gh label create "openvino" --color "00C7FD" --description "OpenVINO related"

gh label create "sprint-0" --color "5319E7" --description "Setup"
gh label create "sprint-1" --color "5319E7" --description "Foundation"
gh label create "sprint-2" --color "5319E7" --description "MVP"
gh label create "sprint-3" --color "5319E7" --description "Analytics"
gh label create "sprint-4" --color "5319E7" --description "Production"

gh label create "p0-critical" --color "B60205" --description "Critical"
gh label create "p1-high" --color "D93F0B" --description "High Priority"
gh label create "p2-medium" --color "FBCA04" --description "Medium Priority"
